/**
 * Enhanced Report Template — Enterprise Quality
 * Generates the complete HTML for PSI's premium inspection report.
 * Matches and exceeds the Bonham reference report (PSI-20260319-001).
 *
 * Design principles:
 * - Print-first: Optimized for A4 PDF via HTML-to-PDF conversion
 * - Brand-forward: PSI logo, colors, and identity prominent throughout
 * - Information hierarchy: Clear visual weight guides the reader
 * - Professional typography: Plus Jakarta Sans headings, Inter body
 * - Graceful degradation: Every section handles missing data
 */

import { format } from "date-fns";
import type { AcousticResult, AcousticSegment } from "./services/acoustic-analysis.service";
import { getPSILogoDataUrl } from "./services/logo-embed.service";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface EnhancedReportData {
  // Core inspection data
  inspectionNumber: string;
  completedAt: Date | null;
  confirmedClientName: string | null;
  confirmedAddress: string | null;
  homeAge: string | null;
  pipeMaterial: string | null;
  knownIssues: string | null;
  backupHistory: string | null;
  recentWork: string | null;
  overallCondition: string | null;
  rootIntrusion: { severity?: string; location?: string; notes?: string } | null;
  cracks: { location: string; severity: string; type?: string }[] | null;
  bellies: { location: string; severity: string }[] | null;
  offsetJoints: { location: string; severity: string }[] | null;
  blockages: { location: string; type?: string; severity: string }[] | null;
  pipeConditionRating: number | null;
  connectionToMain: string | null;
  recommendations: string | null;
  urgencyLevel: string | null;
  inspectionDuration: number | null;

  job: {
    clientName: string;
    clientEmail: string;
    clientPhone: string | null;
    propertyAddress: string;
    propertyCity: string;
    propertyState: string;
    propertyZip: string;
    totalPrice: number;
    accessType?: string;
  };

  technician: {
    name: string;
    email: string;
  };

  clientSignature: {
    signerName: string;
    signedAt: Date;
  } | null;

  // Extended measurements (new)
  extendedMeasurements?: {
    totalFootage?: number;
    depthAtFindings?: Record<string, number>;
    diameterTransitions?: string[];
    cameraDirection?: string;
    flowDirection?: string;
    equipmentUsed?: string;
  } | null;

  // Enhanced sections (generated by agent)
  materialContextNarrative?: string | null;
  acousticResult?: AcousticResult | null;
  acousticInterpretation?: string | null;
  conditionNarrative?: string | null;
  limitationsText?: string | null;

  // Asset URLs (generated by agent)
  videoStills?: Array<{
    chapterId: string;
    title: string;
    timestamp: number;
    s3Url: string;
    severity?: string;
    description?: string;
  }> | null;

  surfaceLocatePhotos?: Array<{
    photoUrl: string;
    caption: string;
    photoType: string;
  }> | null;

  mapImageUrl?: string | null;

  // Spectrograph image (base64 data URL)
  spectrogramDataUrl?: string | null;

  // Video link
  videoUrl?: string | null;
  highlightReelUrl?: string | null;
}

// ─── Design Tokens ───────────────────────────────────────────────────────────

const COLORS = {
  // Primary brand
  navy: "#0c2340",
  navyLight: "#1a3a5c",
  blue: "#0369a1",
  blueLight: "#0ea5e9",
  bluePale: "#e0f2fe",
  blueFaint: "#f0f9ff",

  // Condition spectrum
  excellent: "#059669",
  good: "#10b981",
  fair: "#d97706",
  poor: "#ea580c",
  critical: "#dc2626",

  // Severity
  severityInfo: "#6b7280",
  severityMinor: "#0ea5e9",
  severityModerate: "#d97706",
  severityMajor: "#ea580c",
  severityCritical: "#dc2626",

  // Neutrals
  white: "#ffffff",
  gray50: "#f9fafb",
  gray100: "#f3f4f6",
  gray200: "#e5e7eb",
  gray300: "#d1d5db",
  gray400: "#9ca3af",
  gray500: "#6b7280",
  gray600: "#4b5563",
  gray700: "#374151",
  gray800: "#1f2937",
  gray900: "#111827",

  // Accent
  amber50: "#fffbeb",
  amber100: "#fef3c7",
  amber500: "#f59e0b",
  amber600: "#d97706",

  // Acoustic
  acousticBg: "#faf5ff",
  acousticBorder: "#c084fc",
  acousticText: "#6b21a8",
};

// ─── Helper Functions ────────────────────────────────────────────────────────

function getConditionColor(condition: string | null): string {
  switch (condition?.toUpperCase()) {
    case "EXCELLENT": return COLORS.excellent;
    case "GOOD": return COLORS.good;
    case "FAIR": return COLORS.fair;
    case "NEEDS_ATTENTION":
    case "POOR": return COLORS.poor;
    case "CRITICAL": return COLORS.critical;
    default: return COLORS.gray400;
  }
}

function getConditionLabel(condition: string | null): string {
  switch (condition?.toUpperCase()) {
    case "EXCELLENT": return "Excellent";
    case "GOOD": return "Good";
    case "FAIR": return "Fair";
    case "NEEDS_ATTENTION": return "Needs Attention";
    case "CRITICAL": return "Critical";
    default: return "Not Assessed";
  }
}

function getSeverityColor(severity: string): string {
  switch (severity?.toUpperCase()) {
    case "INFO": return COLORS.severityInfo;
    case "MINOR": return COLORS.severityMinor;
    case "MODERATE": return COLORS.severityModerate;
    case "MAJOR": return COLORS.severityMajor;
    case "CRITICAL": return COLORS.severityCritical;
    default: return COLORS.gray500;
  }
}

function formatSeverity(severity: string): string {
  if (!severity) return "Unknown";
  return severity.charAt(0).toUpperCase() + severity.slice(1).toLowerCase();
}

function formatMaterial(material: string | null): string {
  if (!material) return "Unknown";
  return material.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function getUrgencyConfig(urgency: string | null): { label: string; color: string; bg: string } {
  switch (urgency?.toUpperCase()) {
    case "IMMEDIATE":
      return { label: "Immediate Action Required", color: COLORS.white, bg: COLORS.critical };
    case "SOON":
      return { label: "Repair Recommended (1-3 Months)", color: COLORS.white, bg: COLORS.poor };
    case "MONITOR":
      return { label: "Monitor Condition", color: COLORS.gray800, bg: COLORS.amber100 };
    case "NONE":
      return { label: "No Immediate Concerns", color: COLORS.white, bg: COLORS.good };
    default:
      return { label: "Assessment Pending", color: COLORS.gray600, bg: COLORS.gray100 };
  }
}

function formatTimestamp(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}

// ─── Section Renderers ───────────────────────────────────────────────────────

function renderHeader(data: EnhancedReportData): string {
  const inspectionDate = data.completedAt
    ? format(new Date(data.completedAt), "MMMM d, yyyy")
    : "N/A";

  const logoDataUrl = getPSILogoDataUrl();

  return `
  <div class="report-header">
    <div class="header-top">
      <div class="header-logo-area">
        ${logoDataUrl
          ? `<img src="${logoDataUrl}" alt="PSI Logo" class="logo-image" />`
          : `<div class="logo-circle"><span class="logo-text">PSI</span></div>`}
        <div class="company-info">
          <h1 class="company-name">Precision Sewer Inspection</h1>
          <p class="company-tagline">Central Indiana's Trusted Sewer Inspection Experts</p>
        </div>
      </div>
      <div class="header-contact">
        <div class="contact-item">
          <span class="contact-icon">📞</span>
          <span>(317) 620-3858</span>
        </div>
        <div class="contact-item">
          <span class="contact-icon">✉</span>
          <span>booking@precisionsewerinspections.com</span>
        </div>
        <div class="contact-item">
          <span class="contact-icon">🌐</span>
          <span>www.precisionsewerinspections.com</span>
        </div>
      </div>
    </div>
    <div class="header-title-bar">
      <div class="title-left">
        <h2 class="report-title">Sewer Line Inspection Report</h2>
        <p class="report-subtitle">Comprehensive Camera Inspection with Acoustic Material Analysis</p>
      </div>
      <div class="title-right">
        <div class="report-number-badge">
          <span class="report-number-label">Report</span>
          <span class="report-number-value">#${data.inspectionNumber}</span>
        </div>
        <div class="report-date">${inspectionDate}</div>
      </div>
    </div>
  </div>`;
}

function renderPropertyInfo(data: EnhancedReportData): string {
  const inspectionDate = data.completedAt
    ? format(new Date(data.completedAt), "MMMM d, yyyy")
    : "N/A";

  return `
  <div class="section">
    <div class="section-header">
      <div class="section-icon">🏠</div>
      <h2 class="section-title">Property & Client Information</h2>
    </div>
    <div class="info-card">
      <div class="info-grid-3">
        <div class="info-block">
          <div class="info-block-header">Property</div>
          <div class="info-field">
            <span class="field-label">Address</span>
            <span class="field-value">${data.job.propertyAddress}</span>
          </div>
          <div class="info-field">
            <span class="field-label">City/State</span>
            <span class="field-value">${data.job.propertyCity}, ${data.job.propertyState} ${data.job.propertyZip}</span>
          </div>
          <div class="info-field">
            <span class="field-label">Home Age</span>
            <span class="field-value">${data.homeAge || "Not specified"}</span>
          </div>
        </div>
        <div class="info-block">
          <div class="info-block-header">Client</div>
          <div class="info-field">
            <span class="field-label">Name</span>
            <span class="field-value">${data.confirmedClientName || data.job.clientName}</span>
          </div>
          <div class="info-field">
            <span class="field-label">Email</span>
            <span class="field-value">${data.job.clientEmail}</span>
          </div>
          ${data.job.clientPhone ? `
          <div class="info-field">
            <span class="field-label">Phone</span>
            <span class="field-value">${data.job.clientPhone}</span>
          </div>` : ""}
        </div>
        <div class="info-block">
          <div class="info-block-header">Inspection</div>
          <div class="info-field">
            <span class="field-label">Date</span>
            <span class="field-value">${inspectionDate}</span>
          </div>
          <div class="info-field">
            <span class="field-label">Inspector</span>
            <span class="field-value">${data.technician.name}</span>
          </div>
          <div class="info-field">
            <span class="field-label">Duration</span>
            <span class="field-value">${data.inspectionDuration ? `${data.inspectionDuration} min` : "N/A"}</span>
          </div>
          <div class="info-field">
            <span class="field-label">Access</span>
            <span class="field-value">${data.job.accessType?.replace("_", " ") || "Cleanout"}</span>
          </div>
        </div>
      </div>
      <div class="pipe-material-bar">
        <span class="material-label">Pipe Material Identified:</span>
        <span class="material-value">${formatMaterial(data.pipeMaterial)}</span>
        ${data.extendedMeasurements?.totalFootage ? `
        <span class="material-divider">|</span>
        <span class="material-label">Total Footage:</span>
        <span class="material-value">${data.extendedMeasurements.totalFootage} ft</span>` : ""}
        ${data.extendedMeasurements?.equipmentUsed ? `
        <span class="material-divider">|</span>
        <span class="material-label">Equipment:</span>
        <span class="material-value">${data.extendedMeasurements.equipmentUsed}</span>` : ""}
      </div>
    </div>
  </div>`;
}

function renderMaterialContext(data: EnhancedReportData): string {
  if (!data.materialContextNarrative) return "";

  return `
  <div class="section">
    <div class="section-header">
      <div class="section-icon">🔬</div>
      <h2 class="section-title">Material Context</h2>
    </div>
    <div class="narrative-card">
      <div class="narrative-content">
        ${data.materialContextNarrative.split("\n\n").map((p) => `<p>${p.trim()}</p>`).join("")}
      </div>
    </div>
  </div>`;
}

function renderAcousticAnalysis(data: EnhancedReportData): string {
  const acoustic = data.acousticResult;
  if (!acoustic || !acoustic.success || acoustic.segments.length === 0) return "";

  const segmentRows = acoustic.segments
    .map(
      (s) => `
      <tr>
        <td class="acoustic-cell">${s.label}</td>
        <td class="acoustic-cell acoustic-freq">${s.dominantFrequencyHz} Hz</td>
        <td class="acoustic-cell"><span class="acoustic-badge acoustic-${s.resonanceBand.toLowerCase()}">${s.resonanceBand}</span></td>
        <td class="acoustic-cell"><span class="acoustic-badge acoustic-${s.harmonicsBand.toLowerCase()}">${s.harmonicsBand}</span></td>
        <td class="acoustic-cell"><span class="acoustic-badge acoustic-${s.highFreqTail.toLowerCase()}">${s.highFreqTail}</span></td>
      </tr>`
    )
    .join("");

  return `
  <div class="section acoustic-section">
    <div class="section-header">
      <div class="section-icon">🎵</div>
      <h2 class="section-title">Acoustic Material Analysis</h2>
      <span class="section-badge">Supplemental</span>
    </div>
    <div class="acoustic-card">
      <div class="acoustic-summary">
        <div class="acoustic-indicator">
          <span class="indicator-label">Material Indicated</span>
          <span class="indicator-value">${acoustic.materialIndicator}</span>
        </div>
        <div class="acoustic-indicator">
          <span class="indicator-label">Confidence</span>
          <span class="indicator-value confidence-${acoustic.confidence}">${acoustic.confidence.charAt(0).toUpperCase() + acoustic.confidence.slice(1)}</span>
        </div>
      </div>

      ${data.spectrogramDataUrl ? `
      <div class="spectrogram-container">
        <img src="${data.spectrogramDataUrl}" alt="Acoustic Frequency Analysis" class="spectrogram-image" />
        <p class="spectrogram-caption">Frequency analysis of camera audio during inspection traverse</p>
      </div>` : acoustic.spectrogramUrl ? `
      <div class="spectrogram-container">
        <img src="${acoustic.spectrogramUrl}" alt="Acoustic Spectrogram" class="spectrogram-image" />
        <p class="spectrogram-caption">Frequency spectrogram of camera audio during inspection traverse</p>
      </div>` : ""}

      <table class="acoustic-table">
        <thead>
          <tr>
            <th class="acoustic-th">Inspection Segment</th>
            <th class="acoustic-th">Dominant Freq.</th>
            <th class="acoustic-th">Resonance (2-5 kHz)</th>
            <th class="acoustic-th">Harmonics (5-10 kHz)</th>
            <th class="acoustic-th">High-Freq Tail</th>
          </tr>
        </thead>
        <tbody>${segmentRows}</tbody>
      </table>

      ${data.acousticInterpretation ? `
      <div class="acoustic-interpretation">
        <p class="interpretation-label">Analysis Interpretation</p>
        <p class="interpretation-text">${data.acousticInterpretation}</p>
      </div>` : ""}
    </div>
  </div>`;
}

function renderConditionAssessment(data: EnhancedReportData): string {
  const conditionColor = getConditionColor(data.overallCondition);
  const conditionLabel = getConditionLabel(data.overallCondition);
  const urgency = getUrgencyConfig(data.urgencyLevel);

  return `
  <div class="section page-break-before">
    <div class="section-header">
      <div class="section-icon">📊</div>
      <h2 class="section-title">Overall Condition Assessment</h2>
    </div>
    <div class="assessment-card">
      <div class="assessment-top">
        <div class="condition-display">
          <div class="condition-circle" style="background-color: ${conditionColor};">
            <span class="condition-letter">${conditionLabel.charAt(0)}</span>
          </div>
          <div class="condition-details">
            <span class="condition-label">${conditionLabel}</span>
            ${data.pipeConditionRating ? `
            <div class="rating-display">
              <div class="rating-dots">
                ${[1, 2, 3, 4, 5].map((n) => `<span class="rating-dot ${n <= data.pipeConditionRating! ? "filled" : ""}" style="${n <= data.pipeConditionRating! ? `background-color: ${conditionColor};` : ""}"></span>`).join("")}
              </div>
              <span class="rating-text">${data.pipeConditionRating}/5</span>
            </div>` : ""}
          </div>
        </div>
        <div class="urgency-display" style="background-color: ${urgency.bg}; color: ${urgency.color};">
          ${urgency.label}
        </div>
      </div>
      ${data.conditionNarrative ? `
      <div class="condition-narrative">
        ${data.conditionNarrative.split("\n\n").map((p) => `<p>${p.trim()}</p>`).join("")}
      </div>` : ""}
    </div>
  </div>`;
}

function renderDetailedFindings(data: EnhancedReportData): string {
  const findings: Array<{
    type: string;
    items: Array<{ location: string; severity: string; type?: string; notes?: string }>;
  }> = [];

  if (data.rootIntrusion?.severity) {
    findings.push({
      type: "Root Intrusion",
      items: [{
        location: data.rootIntrusion.location || "Various locations",
        severity: data.rootIntrusion.severity,
        notes: data.rootIntrusion.notes,
      }],
    });
  }

  if (data.cracks?.length) {
    findings.push({ type: "Cracks", items: data.cracks });
  }
  if (data.bellies?.length) {
    findings.push({ type: "Bellies (Low Spots)", items: data.bellies });
  }
  if (data.offsetJoints?.length) {
    findings.push({ type: "Offset Joints", items: data.offsetJoints });
  }
  if (data.blockages?.length) {
    findings.push({ type: "Blockages", items: data.blockages.map((b) => ({ ...b, type: b.type })) });
  }

  const totalFindings = findings.reduce((sum, f) => sum + f.items.length, 0);

  // Build findings rows with optional video stills
  const findingsHTML = findings.length === 0
    ? `<div class="no-findings">
        <span class="no-findings-icon">✓</span>
        <span class="no-findings-text">No significant defects observed during inspection</span>
      </div>`
    : findings
        .map((finding) => {
          const itemRows = finding.items
            .map((item) => {
              // Find matching video still
              const still = data.videoStills?.find(
                (vs) => vs.title.toLowerCase().includes(finding.type.toLowerCase().split(" ")[0])
              );

              return `
              <div class="finding-item">
                ${still ? `
                <div class="finding-image-container">
                  <img src="${still.s3Url}" alt="${still.title}" class="finding-image" />
                  <span class="finding-image-timestamp">${formatTimestamp(still.timestamp)}</span>
                </div>` : ""}
                <div class="finding-details">
                  <div class="finding-meta">
                    <span class="finding-type-badge">${finding.type}</span>
                    <span class="finding-severity-badge" style="background-color: ${getSeverityColor(item.severity)}; color: white;">
                      ${formatSeverity(item.severity)}
                    </span>
                  </div>
                  <div class="finding-location">
                    <span class="location-label">Location:</span> ${item.location}
                  </div>
                  ${item.type ? `<div class="finding-subtype"><span class="location-label">Type:</span> ${item.type}</div>` : ""}
                  ${item.notes ? `<div class="finding-notes">${item.notes}</div>` : ""}
                </div>
              </div>`;
            })
            .join("");

          return itemRows;
        })
        .join("");

  return `
  <div class="section">
    <div class="section-header">
      <div class="section-icon">🔍</div>
      <h2 class="section-title">Detailed Findings</h2>
      <span class="findings-count">${totalFindings} finding${totalFindings !== 1 ? "s" : ""}</span>
    </div>
    <div class="findings-card">
      ${findingsHTML}
    </div>
    ${data.connectionToMain ? `
    <div class="connection-note">
      <span class="connection-label">Connection to Main Sewer:</span>
      <span class="connection-value">${data.connectionToMain}</span>
    </div>` : ""}
  </div>`;
}

function renderVideoStillsGallery(data: EnhancedReportData): string {
  if (!data.videoStills?.length) return "";

  const stills = data.videoStills
    .map(
      (still) => `
      <div class="still-card">
        <img src="${still.s3Url}" alt="${still.title}" class="still-image" />
        <div class="still-info">
          <span class="still-title">${still.title}</span>
          <span class="still-timestamp">${formatTimestamp(still.timestamp)}</span>
          ${still.severity ? `<span class="still-severity" style="color: ${getSeverityColor(still.severity)};">${formatSeverity(still.severity)}</span>` : ""}
        </div>
        ${still.description ? `<p class="still-description">${still.description}</p>` : ""}
      </div>`
    )
    .join("");

  return `
  <div class="section page-break-before">
    <div class="section-header">
      <div class="section-icon">📸</div>
      <h2 class="section-title">Video Still Captures</h2>
    </div>
    <div class="stills-grid">
      ${stills}
    </div>
  </div>`;
}

function renderSurfaceLocate(data: EnhancedReportData): string {
  if (!data.surfaceLocatePhotos?.length) return "";

  const photos = data.surfaceLocatePhotos
    .map(
      (photo) => `
      <div class="locate-card">
        <img src="${photo.photoUrl}" alt="${photo.caption}" class="locate-image" />
        <p class="locate-caption">${photo.caption}</p>
      </div>`
    )
    .join("");

  return `
  <div class="section">
    <div class="section-header">
      <div class="section-icon">📍</div>
      <h2 class="section-title">Surface Locate Documentation</h2>
    </div>
    <div class="locate-grid">
      ${photos}
    </div>
  </div>`;
}

function renderMunicipalMap(data: EnhancedReportData): string {
  if (!data.mapImageUrl) return "";

  return `
  <div class="section">
    <div class="section-header">
      <div class="section-icon">🗺️</div>
      <h2 class="section-title">Municipal Sewer Map</h2>
    </div>
    <div class="map-card">
      <img src="${data.mapImageUrl}" alt="Municipal Sewer Map" class="map-image" />
      <p class="map-caption">
        Municipal sewer infrastructure map for ${data.job.propertyAddress}, ${data.job.propertyCity}.
        Source: City of Indianapolis MapIndy GIS.
        <span class="map-note">Green lines indicate sanitary sewer mains. Property lateral connection shown where visible.</span>
      </p>
    </div>
  </div>`;
}

function renderMeasurements(data: EnhancedReportData): string {
  const ext = data.extendedMeasurements;
  if (!ext) return "";

  const hasData = ext.totalFootage || ext.cameraDirection || ext.flowDirection || ext.diameterTransitions?.length;
  if (!hasData) return "";

  return `
  <div class="section">
    <div class="section-header">
      <div class="section-icon">📏</div>
      <h2 class="section-title">Precise Measurements</h2>
    </div>
    <div class="measurements-card">
      <div class="measurements-grid">
        ${ext.totalFootage ? `
        <div class="measurement-item">
          <span class="measurement-value">${ext.totalFootage}</span>
          <span class="measurement-unit">ft</span>
          <span class="measurement-label">Total Footage Inspected</span>
        </div>` : ""}
        ${ext.cameraDirection ? `
        <div class="measurement-item">
          <span class="measurement-value-text">${ext.cameraDirection}</span>
          <span class="measurement-label">Camera Direction</span>
        </div>` : ""}
        ${ext.flowDirection ? `
        <div class="measurement-item">
          <span class="measurement-value-text">${ext.flowDirection}</span>
          <span class="measurement-label">Flow Direction</span>
        </div>` : ""}
      </div>
      ${ext.diameterTransitions?.length ? `
      <div class="diameter-transitions">
        <span class="transitions-label">Diameter Transitions:</span>
        ${ext.diameterTransitions.map((t) => `<span class="transition-badge">${t}</span>`).join("")}
      </div>` : ""}
      ${ext.depthAtFindings && Object.keys(ext.depthAtFindings).length > 0 ? `
      <div class="depth-table">
        <table class="data-table">
          <thead>
            <tr><th>Finding Location</th><th>Depth from Surface</th></tr>
          </thead>
          <tbody>
            ${Object.entries(ext.depthAtFindings).map(([loc, depth]) => `<tr><td>${loc}</td><td>${depth} ft</td></tr>`).join("")}
          </tbody>
        </table>
      </div>` : ""}
    </div>
  </div>`;
}

function renderRecommendations(data: EnhancedReportData): string {
  if (!data.recommendations) return "";

  return `
  <div class="section page-break-before">
    <div class="section-header">
      <div class="section-icon">💡</div>
      <h2 class="section-title">Recommendations</h2>
    </div>
    <div class="recommendations-card">
      <div class="recommendations-content">
        ${data.recommendations}
      </div>
    </div>
  </div>`;
}

function renderLimitations(data: EnhancedReportData): string {
  if (!data.limitationsText) return "";

  return `
  <div class="section">
    <div class="section-header">
      <div class="section-icon">⚠️</div>
      <h2 class="section-title">Limitations & Exclusions</h2>
    </div>
    <div class="limitations-card">
      ${data.limitationsText}
    </div>
  </div>`;
}

function renderVideoDocumentation(data: EnhancedReportData): string {
  if (!data.videoUrl && !data.highlightReelUrl) return "";

  return `
  <div class="section">
    <div class="section-header">
      <div class="section-icon">🎬</div>
      <h2 class="section-title">Video Documentation</h2>
    </div>
    <div class="video-card">
      <p class="video-note">Complete video documentation of this inspection is included with your report delivery.</p>
      <div class="video-links">
        ${data.videoUrl ? `
        <a href="${data.videoUrl}" class="video-link" target="_blank" rel="noopener">
          <span class="video-link-icon">📹</span>
          <span class="video-link-text">
            <strong>Full Inspection Video</strong>
            <span class="video-link-sub">Complete camera traverse recording</span>
          </span>
        </a>` : ""}
        ${data.highlightReelUrl ? `
        <a href="${data.highlightReelUrl}" class="video-link" target="_blank" rel="noopener">
          <span class="video-link-icon">⭐</span>
          <span class="video-link-text">
            <strong>Highlight Reel</strong>
            <span class="video-link-sub">Key findings summary video</span>
          </span>
        </a>` : ""}
      </div>
    </div>
  </div>`;
}

function renderVerification(data: EnhancedReportData): string {
  return `
  <div class="section">
    <div class="section-header">
      <div class="section-icon">✅</div>
      <h2 class="section-title">Inspection Verification</h2>
    </div>
    <div class="verification-card">
      <div class="verification-grid">
        <div class="verification-item">
          <span class="verification-label">Inspected By</span>
          <span class="verification-value">${data.technician.name}</span>
          <span class="verification-sub">Certified Sewer Inspector</span>
        </div>
        <div class="verification-item">
          <span class="verification-label">Report Generated</span>
          <span class="verification-value">${format(new Date(), "MMMM d, yyyy")}</span>
        </div>
        ${data.clientSignature ? `
        <div class="verification-item">
          <span class="verification-label">Client Acknowledgment</span>
          <span class="verification-value">${data.clientSignature.signerName}</span>
          <span class="verification-sub">${format(new Date(data.clientSignature.signedAt), "MMMM d, yyyy 'at' h:mm a")}</span>
        </div>` : ""}
      </div>
    </div>
  </div>`;
}

function renderDisclaimers(data: EnhancedReportData): string {
  const hasAcoustic = data.acousticResult?.success && data.acousticResult.segments.length > 0;

  return `
  <div class="section disclaimers-section">
    <div class="section-header">
      <div class="section-icon">📋</div>
      <h2 class="section-title">Disclaimers</h2>
    </div>
    <div class="disclaimer-card">
      <p class="disclaimer-text">
        This report is based on a visual inspection via sewer camera conducted at the time of service.
        The inspection is limited to the accessible portions of the sewer line from the point of entry.
        Hidden defects beyond camera reach, behind obstructions, or below standing water are not covered
        by this inspection. This report does not constitute a warranty or guarantee of the sewer line's
        future condition. Precision Sewer Inspection is an inspection-only company and does not perform
        repairs, ensuring complete objectivity in our assessments.
      </p>
      ${hasAcoustic ? `
      <div class="acoustic-disclaimer">
        <p class="acoustic-disclaimer-title">Acoustic Material Analysis Disclaimer</p>
        <p class="disclaimer-text">
          The acoustic material analysis presented in this report is a supplemental assessment tool
          based on frequency analysis of camera audio during the inspection traverse. This analysis
          provides an indication of pipe material composition but is not a definitive material
          identification method. Acoustic signatures can be influenced by environmental factors
          including water flow, ambient noise, pipe joints, and material transitions. The acoustic
          findings should be considered alongside visual inspection results and any available
          construction records. This analysis does not replace professional material testing when
          definitive identification is required.
        </p>
      </div>` : ""}
    </div>
  </div>`;
}

function renderFooter(data: EnhancedReportData): string {
  const logoDataUrl = getPSILogoDataUrl();

  return `
  <div class="report-footer">
    <div class="footer-brand">
      ${logoDataUrl
        ? `<img src="${logoDataUrl}" alt="PSI" class="footer-logo-image" />`
        : `<div class="footer-logo-circle"><span class="footer-logo-text">PSI</span></div>`}
      <div class="footer-company">
        <span class="footer-company-name">Precision Sewer Inspection</span>
        <span class="footer-company-address">Nashville, IN 47448</span>
      </div>
    </div>
    <div class="footer-contact">
      <span>(317) 620-3858</span>
      <span>•</span>
      <span>booking@precisionsewerinspections.com</span>
      <span>•</span>
      <span>www.precisionsewerinspections.com</span>
    </div>
    <div class="footer-legal">
      <span>Report #${data.inspectionNumber}</span>
      <span>•</span>
      <span>Generated ${format(new Date(), "MMMM d, yyyy")}</span>
      <span>•</span>
      <span>© ${new Date().getFullYear()} Precision Sewer Inspection. All rights reserved.</span>
    </div>
  </div>`;
}

// ─── Stylesheet ──────────────────────────────────────────────────────────────

function getStylesheet(): string {
  return `
  <style>
    /* ── Reset & Base ── */
    @page {
      size: A4;
      margin: 0;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Inter', 'Helvetica Neue', Helvetica, Arial, sans-serif;
      color: ${COLORS.gray800};
      line-height: 1.6;
      font-size: 13px;
      background: ${COLORS.white};
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    h1, h2, h3, h4 {
      font-family: 'Plus Jakarta Sans', 'Inter', 'Helvetica Neue', sans-serif;
      line-height: 1.3;
    }
    p { margin-bottom: 8px; }
    p:last-child { margin-bottom: 0; }

    /* ── Header ── */
    .report-header {
      background: linear-gradient(135deg, ${COLORS.navy} 0%, ${COLORS.navyLight} 50%, ${COLORS.blue} 100%);
      color: ${COLORS.white};
      padding: 0;
    }
    .header-top {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 24px 32px 16px;
    }
    .header-logo-area {
      display: flex;
      align-items: center;
      gap: 16px;
    }
    .logo-image {
      width: 56px; height: 56px; border-radius: 50%;
      object-fit: cover; border: 2px solid rgba(255,255,255,0.3);
    }
    .logo-circle {
      width: 56px;
      height: 56px;
      border-radius: 50%;
      background: rgba(255,255,255,0.15);
      border: 2px solid rgba(255,255,255,0.3);
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .logo-text {
      font-family: 'Plus Jakarta Sans', sans-serif;
      font-weight: 800;
      font-size: 20px;
      letter-spacing: 2px;
    }
    .company-name {
      font-size: 22px;
      font-weight: 700;
      letter-spacing: -0.3px;
    }
    .company-tagline {
      font-size: 12px;
      opacity: 0.8;
      margin-top: 2px;
    }
    .header-contact {
      text-align: right;
      font-size: 11px;
      opacity: 0.85;
    }
    .contact-item {
      display: flex;
      align-items: center;
      justify-content: flex-end;
      gap: 6px;
      margin-bottom: 3px;
    }
    .contact-icon { font-size: 12px; }
    .header-title-bar {
      background: rgba(0,0,0,0.15);
      padding: 16px 32px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .report-title {
      font-size: 18px;
      font-weight: 700;
    }
    .report-subtitle {
      font-size: 11px;
      opacity: 0.75;
      margin-top: 2px;
    }
    .title-right { text-align: right; }
    .report-number-badge {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      background: rgba(255,255,255,0.15);
      padding: 6px 14px;
      border-radius: 6px;
      border: 1px solid rgba(255,255,255,0.2);
    }
    .report-number-label { font-size: 10px; text-transform: uppercase; opacity: 0.7; }
    .report-number-value { font-size: 15px; font-weight: 700; letter-spacing: 0.5px; }
    .report-date { font-size: 11px; opacity: 0.7; margin-top: 4px; }

    /* ── Sections ── */
    .section {
      padding: 20px 32px;
      page-break-inside: avoid;
    }
    .section-header {
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 14px;
      padding-bottom: 8px;
      border-bottom: 2px solid ${COLORS.bluePale};
    }
    .section-icon { font-size: 18px; }
    .section-title {
      font-size: 16px;
      font-weight: 700;
      color: ${COLORS.navy};
      flex: 1;
    }
    .section-badge {
      font-size: 10px;
      text-transform: uppercase;
      letter-spacing: 1px;
      padding: 3px 10px;
      border-radius: 10px;
      background: ${COLORS.acousticBg};
      color: ${COLORS.acousticText};
      font-weight: 600;
    }
    .findings-count {
      font-size: 12px;
      color: ${COLORS.gray500};
      font-weight: 500;
    }

    /* ── Info Card ── */
    .info-card {
      background: ${COLORS.gray50};
      border: 1px solid ${COLORS.gray200};
      border-radius: 8px;
      overflow: hidden;
    }
    .info-grid-3 {
      display: grid;
      grid-template-columns: 1fr 1fr 1fr;
      gap: 0;
    }
    .info-block {
      padding: 14px 16px;
      border-right: 1px solid ${COLORS.gray200};
    }
    .info-block:last-child { border-right: none; }
    .info-block-header {
      font-size: 10px;
      text-transform: uppercase;
      letter-spacing: 1.5px;
      color: ${COLORS.blue};
      font-weight: 700;
      margin-bottom: 10px;
    }
    .info-field { margin-bottom: 6px; }
    .field-label {
      display: block;
      font-size: 10px;
      color: ${COLORS.gray500};
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .field-value {
      display: block;
      font-size: 13px;
      font-weight: 500;
      color: ${COLORS.gray800};
    }
    .pipe-material-bar {
      background: ${COLORS.bluePale};
      padding: 10px 16px;
      display: flex;
      align-items: center;
      gap: 8px;
      font-size: 12px;
      border-top: 1px solid ${COLORS.gray200};
    }
    .material-label { color: ${COLORS.gray600}; }
    .material-value { font-weight: 600; color: ${COLORS.navy}; }
    .material-divider { color: ${COLORS.gray300}; }

    /* ── Narrative Card ── */
    .narrative-card {
      background: ${COLORS.gray50};
      border: 1px solid ${COLORS.gray200};
      border-radius: 8px;
      padding: 18px 20px;
    }
    .narrative-content p {
      font-size: 13px;
      line-height: 1.7;
      color: ${COLORS.gray700};
      margin-bottom: 10px;
    }

    /* ── Acoustic Section ── */
    .acoustic-card {
      background: ${COLORS.white};
      border: 1px solid ${COLORS.gray200};
      border-radius: 8px;
      overflow: hidden;
    }
    .acoustic-summary {
      display: flex;
      gap: 24px;
      padding: 16px 20px;
      background: ${COLORS.acousticBg};
      border-bottom: 1px solid ${COLORS.gray200};
    }
    .acoustic-indicator { }
    .indicator-label {
      display: block;
      font-size: 10px;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: ${COLORS.gray500};
      margin-bottom: 2px;
    }
    .indicator-value {
      font-size: 18px;
      font-weight: 700;
      color: ${COLORS.navy};
    }
    .confidence-high { color: ${COLORS.excellent}; }
    .confidence-medium { color: ${COLORS.fair}; }
    .confidence-low { color: ${COLORS.gray400}; }
    .spectrogram-container {
      padding: 16px 20px;
      text-align: center;
    }
    .spectrogram-image {
      max-width: 100%;
      border-radius: 4px;
      border: 1px solid ${COLORS.gray200};
    }
    .spectrogram-caption {
      font-size: 10px;
      color: ${COLORS.gray500};
      margin-top: 6px;
    }
    .acoustic-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 12px;
    }
    .acoustic-th {
      padding: 10px 14px;
      text-align: left;
      background: ${COLORS.gray100};
      color: ${COLORS.gray600};
      font-weight: 600;
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      border-bottom: 1px solid ${COLORS.gray200};
    }
    .acoustic-cell {
      padding: 10px 14px;
      border-bottom: 1px solid ${COLORS.gray100};
    }
    .acoustic-freq { font-weight: 600; font-variant-numeric: tabular-nums; }
    .acoustic-badge {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: 500;
    }
    .acoustic-present { background: #dcfce7; color: #166534; }
    .acoustic-absent { background: ${COLORS.gray100}; color: ${COLORS.gray500}; }
    .acoustic-faint { background: #fef9c3; color: #854d0e; }
    .acoustic-strong { background: #dbeafe; color: #1e40af; }
    .acoustic-interpretation {
      padding: 14px 20px;
      background: ${COLORS.blueFaint};
      border-top: 1px solid ${COLORS.gray200};
    }
    .interpretation-label {
      font-size: 10px;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: ${COLORS.blue};
      font-weight: 600;
      margin-bottom: 4px;
    }
    .interpretation-text {
      font-size: 13px;
      color: ${COLORS.gray700};
      line-height: 1.6;
    }

    /* ── Assessment Card ── */
    .assessment-card {
      background: ${COLORS.white};
      border: 1px solid ${COLORS.gray200};
      border-radius: 8px;
      overflow: hidden;
    }
    .assessment-top {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 20px;
      background: ${COLORS.gray50};
      border-bottom: 1px solid ${COLORS.gray200};
    }
    .condition-display { display: flex; align-items: center; gap: 14px; }
    .condition-circle {
      width: 52px;
      height: 52px;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .condition-letter {
      font-size: 24px;
      font-weight: 800;
      color: ${COLORS.white};
    }
    .condition-label {
      font-size: 20px;
      font-weight: 700;
      color: ${COLORS.gray800};
    }
    .rating-display { display: flex; align-items: center; gap: 8px; margin-top: 4px; }
    .rating-dots { display: flex; gap: 4px; }
    .rating-dot {
      width: 14px;
      height: 14px;
      border-radius: 50%;
      background: ${COLORS.gray200};
    }
    .rating-dot.filled { }
    .rating-text { font-size: 13px; color: ${COLORS.gray500}; font-weight: 500; }
    .urgency-display {
      padding: 8px 18px;
      border-radius: 6px;
      font-size: 13px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .condition-narrative {
      padding: 16px 20px;
    }
    .condition-narrative p {
      font-size: 13px;
      line-height: 1.7;
      color: ${COLORS.gray700};
      margin-bottom: 8px;
    }

    /* ── Findings ── */
    .findings-card {
      background: ${COLORS.white};
      border: 1px solid ${COLORS.gray200};
      border-radius: 8px;
      overflow: hidden;
    }
    .finding-item {
      display: flex;
      gap: 16px;
      padding: 14px 18px;
      border-bottom: 1px solid ${COLORS.gray100};
    }
    .finding-item:last-child { border-bottom: none; }
    .finding-image-container {
      position: relative;
      flex-shrink: 0;
    }
    .finding-image {
      width: 120px;
      height: 90px;
      object-fit: cover;
      border-radius: 6px;
      border: 1px solid ${COLORS.gray200};
    }
    .finding-image-timestamp {
      position: absolute;
      bottom: 4px;
      right: 4px;
      background: rgba(0,0,0,0.7);
      color: white;
      font-size: 10px;
      padding: 2px 6px;
      border-radius: 3px;
      font-variant-numeric: tabular-nums;
    }
    .finding-details { flex: 1; }
    .finding-meta { display: flex; gap: 8px; margin-bottom: 6px; }
    .finding-type-badge {
      font-size: 11px;
      font-weight: 600;
      color: ${COLORS.navy};
      background: ${COLORS.bluePale};
      padding: 2px 8px;
      border-radius: 4px;
    }
    .finding-severity-badge {
      font-size: 11px;
      font-weight: 600;
      padding: 2px 8px;
      border-radius: 4px;
    }
    .finding-location { font-size: 13px; color: ${COLORS.gray700}; }
    .finding-subtype { font-size: 12px; color: ${COLORS.gray600}; margin-top: 2px; }
    .finding-notes { font-size: 12px; color: ${COLORS.gray500}; margin-top: 4px; font-style: italic; }
    .location-label { font-weight: 600; color: ${COLORS.gray600}; }
    .no-findings {
      display: flex;
      align-items: center;
      gap: 10px;
      padding: 20px;
      color: ${COLORS.excellent};
    }
    .no-findings-icon { font-size: 20px; }
    .no-findings-text { font-size: 14px; font-weight: 500; }
    .connection-note {
      margin-top: 10px;
      padding: 10px 16px;
      background: ${COLORS.blueFaint};
      border: 1px solid ${COLORS.bluePale};
      border-radius: 6px;
      font-size: 13px;
    }
    .connection-label { font-weight: 600; color: ${COLORS.navy}; }
    .connection-value { color: ${COLORS.gray700}; }

    /* ── Video Stills Gallery ── */
    .stills-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 12px;
    }
    .still-card {
      border: 1px solid ${COLORS.gray200};
      border-radius: 8px;
      overflow: hidden;
    }
    .still-image {
      width: 100%;
      height: 160px;
      object-fit: cover;
    }
    .still-info {
      padding: 8px 12px;
      display: flex;
      align-items: center;
      gap: 8px;
      background: ${COLORS.gray50};
    }
    .still-title { font-size: 12px; font-weight: 600; flex: 1; }
    .still-timestamp { font-size: 11px; color: ${COLORS.gray500}; font-variant-numeric: tabular-nums; }
    .still-severity { font-size: 11px; font-weight: 600; }
    .still-description { padding: 6px 12px 10px; font-size: 12px; color: ${COLORS.gray600}; }

    /* ── Surface Locate ── */
    .locate-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 12px;
    }
    .locate-card {
      border: 1px solid ${COLORS.gray200};
      border-radius: 8px;
      overflow: hidden;
    }
    .locate-image {
      width: 100%;
      height: 180px;
      object-fit: cover;
    }
    .locate-caption {
      padding: 8px 12px;
      font-size: 12px;
      color: ${COLORS.gray600};
      background: ${COLORS.gray50};
    }

    /* ── Map ── */
    .map-card {
      border: 1px solid ${COLORS.gray200};
      border-radius: 8px;
      overflow: hidden;
    }
    .map-image {
      width: 100%;
      max-height: 400px;
      object-fit: contain;
    }
    .map-caption {
      padding: 10px 16px;
      font-size: 11px;
      color: ${COLORS.gray500};
      background: ${COLORS.gray50};
      border-top: 1px solid ${COLORS.gray200};
    }
    .map-note { display: block; margin-top: 4px; font-style: italic; }

    /* ── Measurements ── */
    .measurements-card {
      background: ${COLORS.gray50};
      border: 1px solid ${COLORS.gray200};
      border-radius: 8px;
      padding: 18px 20px;
    }
    .measurements-grid {
      display: flex;
      gap: 32px;
      margin-bottom: 12px;
    }
    .measurement-item { text-align: center; }
    .measurement-value {
      font-size: 32px;
      font-weight: 800;
      color: ${COLORS.navy};
      line-height: 1;
    }
    .measurement-unit {
      font-size: 16px;
      font-weight: 600;
      color: ${COLORS.blue};
    }
    .measurement-value-text {
      font-size: 18px;
      font-weight: 700;
      color: ${COLORS.navy};
    }
    .measurement-label {
      display: block;
      font-size: 10px;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: ${COLORS.gray500};
      margin-top: 4px;
    }
    .diameter-transitions {
      display: flex;
      align-items: center;
      gap: 8px;
      flex-wrap: wrap;
    }
    .transitions-label { font-size: 12px; color: ${COLORS.gray600}; font-weight: 600; }
    .transition-badge {
      font-size: 11px;
      padding: 3px 10px;
      background: ${COLORS.bluePale};
      color: ${COLORS.navy};
      border-radius: 4px;
      font-weight: 500;
    }
    .data-table {
      width: 100%;
      border-collapse: collapse;
      font-size: 12px;
      margin-top: 10px;
    }
    .data-table th {
      padding: 8px 12px;
      text-align: left;
      background: ${COLORS.gray100};
      color: ${COLORS.gray600};
      font-weight: 600;
      font-size: 11px;
      border-bottom: 1px solid ${COLORS.gray200};
    }
    .data-table td {
      padding: 8px 12px;
      border-bottom: 1px solid ${COLORS.gray100};
    }

    /* ── Recommendations ── */
    .recommendations-card {
      background: ${COLORS.amber50};
      border: 1px solid ${COLORS.amber500};
      border-left: 4px solid ${COLORS.amber500};
      border-radius: 8px;
      padding: 16px 20px;
    }
    .recommendations-content {
      font-size: 13px;
      line-height: 1.7;
      color: ${COLORS.gray700};
    }

    /* ── Limitations ── */
    .limitations-card {
      background: ${COLORS.gray50};
      border: 1px solid ${COLORS.gray200};
      border-radius: 8px;
      padding: 16px 20px;
      font-size: 12px;
      line-height: 1.7;
      color: ${COLORS.gray600};
    }

    /* ── Video Documentation ── */
    .video-card {
      background: ${COLORS.blueFaint};
      border: 1px solid ${COLORS.bluePale};
      border-radius: 8px;
      padding: 16px 20px;
    }
    .video-note { font-size: 13px; color: ${COLORS.gray700}; margin-bottom: 12px; }
    .video-links { display: flex; gap: 12px; flex-wrap: wrap; }
    .video-link {
      display: flex; align-items: center; gap: 10px;
      background: white; border: 1px solid ${COLORS.bluePale}; border-radius: 8px;
      padding: 12px 16px; text-decoration: none; color: ${COLORS.gray800};
      flex: 1; min-width: 200px; transition: border-color 0.2s;
    }
    .video-link:hover { border-color: ${COLORS.blue}; }
    .video-link-icon { font-size: 24px; }
    .video-link-text { display: flex; flex-direction: column; }
    .video-link-text strong { font-size: 13px; color: ${COLORS.navy}; }
    .video-link-sub { font-size: 11px; color: ${COLORS.gray500}; }

    /* ── Verification ── */
    .verification-card {
      background: ${COLORS.gray50};
      border: 1px solid ${COLORS.gray200};
      border-radius: 8px;
      padding: 18px 20px;
    }
    .verification-grid {
      display: flex;
      gap: 32px;
    }
    .verification-item { }
    .verification-label {
      display: block;
      font-size: 10px;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: ${COLORS.gray500};
      margin-bottom: 2px;
    }
    .verification-value {
      font-size: 15px;
      font-weight: 600;
      color: ${COLORS.gray800};
    }
    .verification-sub {
      display: block;
      font-size: 11px;
      color: ${COLORS.gray500};
    }

    /* ── Disclaimers ── */
    .disclaimers-section { page-break-inside: avoid; }
    .disclaimer-card {
      background: ${COLORS.gray50};
      border: 1px solid ${COLORS.gray200};
      border-radius: 8px;
      padding: 16px 20px;
    }
    .disclaimer-text {
      font-size: 11px;
      line-height: 1.7;
      color: ${COLORS.gray500};
    }
    .acoustic-disclaimer {
      margin-top: 12px;
      padding-top: 12px;
      border-top: 1px solid ${COLORS.gray200};
    }
    .acoustic-disclaimer-title {
      font-size: 11px;
      font-weight: 700;
      color: ${COLORS.acousticText};
      margin-bottom: 4px;
    }

    /* ── Footer ── */
    .report-footer {
      background: ${COLORS.navy};
      color: ${COLORS.white};
      padding: 20px 32px;
      text-align: center;
      margin-top: 20px;
    }
    .footer-brand {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 12px;
      margin-bottom: 10px;
    }
    .footer-logo-image {
      width: 32px; height: 32px; border-radius: 50%;
      object-fit: cover; border: 1px solid rgba(255,255,255,0.25);
    }
    .footer-logo-circle {
      width: 32px;
      height: 32px;
      border-radius: 50%;
      background: rgba(255,255,255,0.15);
      border: 1px solid rgba(255,255,255,0.25);
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .footer-logo-text {
      font-family: 'Plus Jakarta Sans', sans-serif;
      font-weight: 800;
      font-size: 12px;
      letter-spacing: 1px;
    }
    .footer-company-name {
      font-weight: 700;
      font-size: 14px;
    }
    .footer-company-address {
      display: block;
      font-size: 11px;
      opacity: 0.7;
    }
    .footer-contact {
      font-size: 11px;
      opacity: 0.8;
      margin-bottom: 6px;
      display: flex;
      justify-content: center;
      gap: 8px;
    }
    .footer-legal {
      font-size: 10px;
      opacity: 0.5;
      display: flex;
      justify-content: center;
      gap: 8px;
    }

    /* ── Utilities ── */
    .page-break-before { page-break-before: always; }
    .page-break-after { page-break-after: always; }

    /* ── Print / PDF Pagination ── */
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }

      /* Force page breaks before major sections */
      .section.page-break-before { page-break-before: always; }

      /* Prevent mid-section splits */
      .section { page-break-inside: avoid; }
      .acoustic-card { page-break-inside: avoid; }
      .acoustic-table { page-break-inside: avoid; }
      .condition-card { page-break-inside: avoid; }
      .findings-card { page-break-inside: avoid; }
      .measurements-card { page-break-inside: avoid; }
      .verification-card { page-break-inside: avoid; }
      .disclaimers-section { page-break-inside: avoid; }
      .video-card { page-break-inside: avoid; }
      .map-card { page-break-inside: avoid; }
      .limitations-card { page-break-inside: avoid; }
      .recommendations-card { page-break-inside: avoid; }

      /* Keep images with their captions */
      .still-card { page-break-inside: avoid; }
      .locate-card { page-break-inside: avoid; }
      .spectrogram-container { page-break-inside: avoid; }

      /* Prevent orphaned headers */
      .section-header { page-break-after: avoid; }
      h2, h3 { page-break-after: avoid; orphans: 3; widows: 3; }

      /* Keep stills grid together when possible, break between cards if needed */
      .stills-grid { page-break-before: avoid; }

      /* Footer stays at bottom of last page */
      .report-footer { page-break-before: auto; page-break-inside: avoid; }

      /* Header only on first page */
      .report-header { page-break-after: avoid; }

      /* Prevent large blank spaces — allow overflow to next page */
      .property-info { page-break-inside: avoid; }
      .info-card { page-break-inside: avoid; }
    }
  </style>`;
}

// ─── Main Export ──────────────────────────────────────────────────────────────

export function generateEnhancedReportHTML(
  data: EnhancedReportData,
  isClientVersion: boolean = true
): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sewer Inspection Report #${data.inspectionNumber} — Precision Sewer Inspection</title>
  ${getStylesheet()}
</head>
<body>
  ${renderHeader(data)}
  ${renderPropertyInfo(data)}
  ${renderMaterialContext(data)}
  ${renderAcousticAnalysis(data)}
  ${renderConditionAssessment(data)}
  ${renderDetailedFindings(data)}
  ${renderVideoStillsGallery(data)}
  ${renderSurfaceLocate(data)}
  ${renderMunicipalMap(data)}
  ${renderMeasurements(data)}
  ${renderRecommendations(data)}
  ${renderLimitations(data)}
  ${renderVideoDocumentation(data)}
  ${renderVerification(data)}
  ${renderDisclaimers(data)}
  ${renderFooter(data)}
</body>
</html>`;
}
